import { AirportInfoModel } from "../../src/models/AirportInfo.mjs";

const airports = [
  {
    _id: "5f9f7b3b9d3b3c1b1c9b4b4c",
    airport_code: "KSEA",
    name: "Seattle-Tacoma Intl",
    location: "Seattle, WA",
    latitude: 47.4498889,
    longitude: -122.3117778,
    timezone: "America/Los_Angeles",
    timezone_offset_sec: -25200,
    elevation_ft: 433,
    classification: 1,
    active: true,
    delay_index_url: "https://flightaware.com/commercial/flightxml/data/airportdelays",
    weather_url: "https://flightaware.com/commercial/flightxml/data/weather",
    satellite: true,
    site: "SEA",
    iata: "SEA",
    icao: "KSEA",
    faa: "SEA",
    type: "large_airport",
    wikipedia: "http://en.wikipedia.org/wiki/Seattle-Tacoma_International_Airport",
    keywords: "SEA, KSEA, Seattle-Tacoma Intl, Boeing Field, King County Intl",
    magneticDeclination: -15.23,
  },
  {
    _id: "5f9f7b3b9d3b3c1b1c9b4b4b",
    airport_code: "KPDX",
    name: "Portland Intl",
    location: "Portland, OR",
    latitude: 45.5887089,
    longitude: -122.5968694,
    timezone: "America/Los_Angeles",
    timezone_offset_sec: -25200,
    elevation_ft: 31,
    classification: 1,
    active: true,
    delay_index_url: "https://flightaware.com/commercial/flightxml/data/airportdelays",
    weather_url: "https://flightaware.com/commercial/flightxml/data/weather",
    satellite: false,
    site: "PDX",
    iata: "PDX",
    icao: "KPDX",
    faa: "PDX",
    type: "large_airport",
    wikipedia: "http://en.wikipedia.org/wiki/Portland_International_Airport",
    keywords: "PDX, KPDX, Portland Intl",
    magneticDeclination: -14.85242,
  },
  {
    _id: "5f9f7b3b9d3b3c1b1c9b4b4d",
    airportCode: "KSLE",
    alternateIdent: "SLE",
    icaoCode: "KSLE",
    iataCode: null,
    lidCode: "SLE",
    name: "Mcnary Fld",
    type: "Airport",
    elevation: 213,
    city: "Salem",
    state: "OR",
    longitude: -123.0025,
    latitude: 44.9095278,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    wikiUrl: "http://en.wikipedia.org/wiki/McNary_Field",
    airportFlightsUrl: "/airports/KSLE/flights",
    alternatives: [],
    magneticDeclination: -14.76194,
    __v: 0,
  },
  {
    _id: "5f9f7b3b9d3b3c1b1c9b4b4e",
    airportCode: "KPDT",
    alternateIdent: "PDT",
    icaoCode: "KPDT",
    iataCode: "PDT",
    lidCode: "PDT",
    name: "Eastern Oregon Rgnl",
    type: "Airport",
    elevation: 1494,
    city: "Pendleton",
    state: "OR",
    longitude: -118.8433686,
    latitude: 45.6950953,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    wikiUrl: "http://en.wikipedia.org/wiki/Eastern_Oregon_Regional_Airport",
    airportFlightsUrl: "/airports/KPDT/flights",
    alternatives: [],
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0ad7249",
    airportCode: "KATL",
    icaoCode: "KATL",
    iataCode: "ATL",
    name: "Hartsfield - Jackson Atlanta International",
    city: "Atlanta",
    state: "Georgia",
    longitude: -84.427864,
    latitude: 33.6367,
    timezone: "America/New_York",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0adb1ce",
    airportCode: "CYVR",
    icaoCode: "CYVR",
    iataCode: "YVR",
    name: "Vancouver International",
    city: "Vancouver ",
    state: "British Columbia",
    longitude: -123.183889,
    latitude: 49.194722,
    timezone: "America/Vancouver",
    countryCode: "CA",
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0ad6f06",
    airportCode: "KBZN",
    icaoCode: "KBZN",
    iataCode: "BZN",
    name: "Bozeman Yellowstone International",
    city: "Bozeman",
    state: "Montana",
    longitude: -111.15026,
    latitude: 45.777236,
    timezone: "America/Denver",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0ad9bd0",
    airportCode: "CYWG",
    icaoCode: "CYWG",
    iataCode: "YWG",
    name: "Winnipeg James Armstrong Richardson International Airport",
    city: "Winnipeg",
    state: "Manitoba",
    longitude: -97.2400944,
    latitude: 49.9100111,
    timezone: "America/Winnipeg",
    countryCode: "CA",
    __v: 0,
  },
  {
    _id: "65db0b6cfede15b9d0ad48a6",
    airportCode: "KDEN",
    icaoCode: "KDEN",
    iataCode: "DEN",
    name: "Denver International",
    city: "Denver",
    state: "Colorado",
    longitude: -104.673167,
    latitude: 39.861667,
    timezone: "America/Denver",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0ad72bc",
    airportCode: "KMCI",
    icaoCode: "KMCI",
    iataCode: "MCI",
    name: "Kansas City International",
    city: "Kansas City",
    state: "Missouri",
    longitude: -94.713889,
    latitude: 39.297611,
    timezone: "America/Chicago",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6cfede15b9d0ad5b1a",
    airportCode: "KDTW",
    icaoCode: "KDTW",
    iataCode: "DTW",
    name: "Detroit Metro Wayne County",
    city: "Detroit",
    state: "Michigan",
    longitude: -83.353393,
    latitude: 42.212431,
    timezone: "America/Detroit",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0ad957b",
    airportCode: "KBIL",
    icaoCode: "KBIL",
    iataCode: "BIL",
    name: "Billings Logan International",
    city: "Billings",
    state: "Montana",
    longitude: -108.543544,
    latitude: 45.807849,
    timezone: "America/Denver",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb208228",
    airportCode: "CYXS",
    icaoCode: "CYXS",
    iataCode: "YXS",
    name: "Prince George Airport",
    city: "Prince George",
    state: "British Columbia",
    longitude: -122.6775528,
    latitude: 53.8840361,
    timezone: "America/Vancouver",
    countryCode: "CA",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb2029fe",
    airportCode: "EDDF",
    icaoCode: "EDDF",
    iataCode: "FRA",
    name: "Frankfurt Main",
    city: "Frankfurt",
    longitude: 8.5704556,
    latitude: 50.0333056,
    timezone: "Europe/Berlin",
    countryCode: "DE",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb207d49",
    airportCode: "EDDL",
    icaoCode: "EDDL",
    iataCode: "DUS",
    name: "Dusseldorf",
    city: "Dusseldorf",
    longitude: 6.7573111,
    latitude: 51.280925,
    timezone: "Europe/Berlin",
    countryCode: "DE",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb207e10",
    airportCode: "EGLL",
    icaoCode: "EGLL",
    iataCode: "LHR",
    name: "London Heathrow",
    city: "London",
    longitude: -0.4613889,
    latitude: 51.4775,
    timezone: "Europe/London",
    countryCode: "GB",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb206a4d",
    airportCode: "EHAM",
    icaoCode: "EHAM",
    iataCode: "AMS",
    name: "Amsterdam Schiphol",
    city: "Amsterdam",
    longitude: 4.7641667,
    latitude: 52.3080556,
    timezone: "Europe/Amsterdam",
    countryCode: "NL",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb206979",
    airportCode: "KBOI",
    icaoCode: "KBOI",
    iataCode: "BOI",
    name: "Boise Air Trml - Gowen Field",
    city: "Boise",
    state: "Idaho",
    longitude: -116.222861,
    latitude: 43.564361,
    timezone: "America/Boise",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb206232",
    airportCode: "KBOS",
    icaoCode: "KBOS",
    iataCode: "BOS",
    name: "General Edward Lawrence Logan International",
    city: "Boston",
    state: "Massachusetts",
    longitude: -71.006389,
    latitude: 42.362944,
    timezone: "America/New_York",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb206eb3",
    airportCode: "KBUR",
    icaoCode: "KBUR",
    iataCode: "BUR",
    name: "Bob Hope",
    city: "Burbank",
    state: "California",
    longitude: -118.358667,
    latitude: 34.200694,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb2057cb",
    airportCode: "KBWI",
    icaoCode: "KBWI",
    iataCode: "BWI",
    name: "Baltimore - Washington International Thurgood Marshall",
    city: "Baltimore",
    state: "Maryland",
    longitude: -76.668991,
    latitude: 39.175728,
    timezone: "America/New_York",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6e79e9b1ccbb209ef6",
    airportCode: "KCLM",
    icaoCode: "KCLM",
    iataCode: "CLM",
    name: "William R Fairchild International",
    city: "Port Angeles",
    state: "Washington",
    longitude: -123.499694,
    latitude: 48.120194,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb207232",
    airportCode: "KDCA",
    icaoCode: "KDCA",
    iataCode: "DCA",
    name: "Ronald Reagan Washington National",
    city: "Washington",
    state: "District of Columbia",
    longitude: -77.037721,
    latitude: 38.85144,
    timezone: "America/New_York",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb20635c",
    airportCode: "KEGE",
    icaoCode: "KEGE",
    iataCode: "EGE",
    name: "Eagle County Regional",
    city: "Eagle",
    state: "Colorado",
    longitude: -106.915944,
    latitude: 39.64275,
    timezone: "America/Denver",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb206372",
    airportCode: "KEUG",
    icaoCode: "KEUG",
    iataCode: "EUG",
    name: "Mahlon Sweet Field ",
    city: "Eugene",
    state: "Oregon",
    longitude: -123.2119722,
    latitude: 44.1245833,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb20405d",
    airportCode: "KGEG",
    icaoCode: "KGEG",
    iataCode: "GEG",
    name: "Spokane International",
    city: "Spokane",
    state: "Washington",
    longitude: -117.535222,
    latitude: 47.619028,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb206fdf",
    airportCode: "KIAH",
    icaoCode: "KIAH",
    iataCode: "IAH",
    name: "George Bush Intcntl - Houston",
    city: "Houston",
    state: "Texas",
    longitude: -95.341443,
    latitude: 29.984435,
    timezone: "America/Chicago",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb2041a1",
    airportCode: "KJAC",
    icaoCode: "KJAC",
    iataCode: "JAC",
    name: "Jackson Hole",
    city: "Jackson",
    state: "Wyoming",
    longitude: -110.73775,
    latitude: 43.607333,
    timezone: "America/Denver",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb203674",
    airportCode: "KJFK",
    icaoCode: "KJFK",
    iataCode: "JFK",
    name: "John F Kennedy International",
    city: "New York",
    state: "New York",
    longitude: -73.778692,
    latitude: 40.639928,
    timezone: "America/New_York",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb202d5e",
    airportCode: "KLAS",
    icaoCode: "KLAS",
    iataCode: "LAS",
    name: "Harry Reid International",
    city: "Las Vegas",
    state: "Nevada",
    longitude: -115.1522361,
    latitude: 36.0800439,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb202e77",
    airportCode: "KLAX",
    icaoCode: "KLAX",
    iataCode: "LAX",
    name: "Los Angeles International",
    city: "Los Angeles",
    state: "California",
    longitude: -118.408049,
    latitude: 33.942496,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb2029c2",
    airportCode: "KMDW",
    icaoCode: "KMDW",
    iataCode: "MDW",
    name: "Chicago Midway International",
    city: "Chicago",
    state: "Illinois",
    longitude: -87.752417,
    latitude: 41.785972,
    timezone: "America/Chicago",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb206304",
    airportCode: "KMFR",
    icaoCode: "KMFR",
    iataCode: "MFR",
    name: "Rogue Valley International–Medford",
    city: "Medford",
    state: "Oregon",
    longitude: -122.8735,
    latitude: 42.3742222,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb2059c8",
    airportCode: "KMSO",
    icaoCode: "KMSO",
    iataCode: "MSO",
    name: "Missoula Montana",
    city: "Missoula",
    state: "Montana",
    longitude: -114.090556,
    latitude: 46.916306,
    timezone: "America/Denver",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb20732d",
    airportCode: "KMSP",
    icaoCode: "KMSP",
    iataCode: "MSP",
    name: "Minneapolis-St Paul International - Wold-Chamberlain",
    city: "Minneapolis",
    state: "Minnesota",
    longitude: -93.221778,
    latitude: 44.881972,
    timezone: "America/Chicago",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb2058dc",
    airportCode: "KOAK",
    icaoCode: "KOAK",
    iataCode: "OAK",
    name: "Metro Oakland International",
    city: "Oakland",
    state: "California",
    longitude: -122.221151,
    latitude: 37.721261,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb202a33",
    airportCode: "KORD",
    icaoCode: "KORD",
    iataCode: "ORD",
    name: "Chicago O'hare International",
    city: "Chicago",
    state: "Illinois",
    longitude: -87.90815,
    latitude: 41.97694,
    timezone: "America/Chicago",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb207ad6",
    airportCode: "KPHX",
    icaoCode: "KPHX",
    iataCode: "PHX",
    name: "Phoenix Sky Harbor International",
    city: "Phoenix",
    state: "Arizona",
    longitude: -112.011583,
    latitude: 33.434278,
    timezone: "America/Phoenix",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb2056b0",
    airportCode: "KPSP",
    icaoCode: "KPSP",
    iataCode: "PSP",
    name: "Palm Springs International",
    city: "Palm Springs",
    state: "California",
    longitude: -116.506694,
    latitude: 33.829667,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb207b19",
    airportCode: "KPUW",
    icaoCode: "KPUW",
    iataCode: "PUW",
    name: "Pullman - Moscow Regional",
    city: "Pullman/moscow",
    state: "Washington",
    longitude: -117.111619,
    latitude: 46.741691,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb207e70",
    airportCode: "KRNO",
    icaoCode: "KRNO",
    iataCode: "RNO",
    name: "Reno - Tahoe International",
    city: "Reno",
    state: "Nevada",
    longitude: -119.768111,
    latitude: 39.499111,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb205711",
    airportCode: "KSAN",
    icaoCode: "KSAN",
    iataCode: "SAN",
    name: "San Diego International",
    city: "San Diego",
    state: "California",
    longitude: -117.189663,
    latitude: 32.733563,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb205864",
    airportCode: "KSAT",
    icaoCode: "KSAT",
    iataCode: "SAT",
    name: "San Antonio International",
    city: "San Antonio",
    state: "Texas",
    longitude: -98.469057,
    latitude: 29.533958,
    timezone: "America/Chicago",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb2059b6",
    airportCode: "KSBP",
    icaoCode: "KSBP",
    iataCode: "SBP",
    name: "San Luis County Regional",
    city: "San Luis Obispo",
    state: "California",
    longitude: -120.642603,
    latitude: 35.237272,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb203f12",
    airportCode: "KSFO",
    icaoCode: "KSFO",
    iataCode: "SFO",
    name: "San Francisco International",
    city: "San Francisco",
    state: "California",
    longitude: -122.375417,
    latitude: 37.618806,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb203f5a",
    airportCode: "KSJC",
    icaoCode: "KSJC",
    iataCode: "SJC",
    name: "Norman Y Mineta San Jose International",
    city: "San Jose",
    state: "California",
    longitude: -121.928621,
    latitude: 37.362995,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb206217",
    airportCode: "KSLC",
    icaoCode: "KSLC",
    iataCode: "SLC",
    name: "Salt Lake City International",
    city: "Salt Lake City",
    state: "Utah",
    longitude: -111.977773,
    latitude: 40.788393,
    timezone: "America/Denver",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb204e18",
    airportCode: "KSNA",
    icaoCode: "KSNA",
    iataCode: "SNA",
    name: "John Wayne - Orange County",
    city: "Santa Ana",
    state: "California",
    longitude: -117.868233,
    latitude: 33.675662,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb207b21",
    airportCode: "KYKM",
    icaoCode: "KYKM",
    iataCode: "YKM",
    name: "Yakima Air Trml - Mcallister Field",
    city: "Yakima",
    state: "Washington",
    longitude: -120.544062,
    latitude: 46.568167,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb202881",
    airportCode: "LFPG",
    icaoCode: "LFPG",
    iataCode: "CDG",
    name: "Paris Charles de Gaulle International",
    city: "Paris",
    longitude: 2.5477778,
    latitude: 49.0097222,
    timezone: "Europe/Paris",
    countryCode: "FR",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb204109",
    airportCode: "MMMY",
    icaoCode: "MMMY",
    iataCode: "MTY",
    name: "Monterrey International",
    city: "Apodaca",
    longitude: -100.1069444,
    latitude: 25.7758583,
    timezone: "America/Monterrey",
    countryCode: "MX",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb207144",
    airportCode: "PAFA",
    icaoCode: "PAFA",
    iataCode: "FAI",
    name: "Fairbanks International",
    city: "Fairbanks",
    state: "Alaska",
    longitude: -147.856667,
    latitude: 64.815356,
    timezone: "America/Anchorage",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb2076ef",
    airportCode: "PAJN",
    icaoCode: "PAJN",
    iataCode: "JNU",
    name: "Juneau International",
    city: "Juneau",
    state: "Alaska",
    longitude: -134.578471,
    latitude: 58.354712,
    timezone: "America/Juneau",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6e79e9b1ccbb20a35b",
    airportCode: "PAKT",
    icaoCode: "PAKT",
    iataCode: "KTN",
    name: "Ketchikan International",
    city: "Ketchikan",
    state: "Alaska",
    longitude: -131.711222,
    latitude: 55.354083,
    timezone: "America/Sitka",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb2043c9",
    airportCode: "PANC",
    icaoCode: "PANC",
    iataCode: "ANC",
    name: "Ted Stevens Anchorage International",
    city: "Anchorage",
    state: "Alaska",
    longitude: -149.998138,
    latitude: 61.174085,
    timezone: "America/Anchorage",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb206474",
    airportCode: "PHNL",
    icaoCode: "PHNL",
    iataCode: "HNL",
    name: "Daniel K Inouye International",
    city: "Honolulu",
    state: "Hawaii",
    longitude: -157.920228,
    latitude: 21.317817,
    timezone: "Pacific/Honolulu",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb2064db",
    airportCode: "PHOG",
    icaoCode: "PHOG",
    iataCode: "OGG",
    name: "Kahului",
    city: "Kahului",
    state: "Hawaii",
    longitude: -156.430459,
    latitude: 20.898649,
    timezone: "Pacific/Honolulu",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6e79e9b1ccbb20a2e3",
    airportCode: "RJAA",
    icaoCode: "RJAA",
    iataCode: "NRT",
    name: "Narita",
    city: "Narita",
    longitude: 140.3855556,
    latitude: 35.7652778,
    timezone: "Asia/Tokyo",
    countryCode: "JP",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb2088ee",
    airportCode: "RJTT",
    icaoCode: "RJTT",
    iataCode: "HND",
    name: "Tokyo International",
    city: "Tokyo ",
    longitude: 139.7811111,
    latitude: 35.5533333,
    timezone: "Asia/Tokyo",
    countryCode: "JP",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb2057ca",
    airportCode: "RKSI",
    icaoCode: "RKSI",
    iataCode: "ICN",
    name: "Seoul Incheon International",
    city: "Incheon",
    longitude: 126.4391667,
    latitude: 37.4625,
    timezone: "Asia/Seoul",
    countryCode: "KR",
    __v: 0,
  },
  {
    _id: "65db0b6d79e9b1ccbb209062",
    airportCode: "TBPB",
    icaoCode: "TBPB",
    iataCode: "BGI",
    name: "Grantley Adams International Airport",
    city: "Bridgetown",
    longitude: -59.4922222,
    latitude: 13.0747222,
    timezone: "America/Barbados",
    countryCode: "BB",
    __v: 0,
  },
  {
    _id: "65db0b6c79e9b1ccbb203a64",
    airportCode: "UUWW",
    icaoCode: "UUWW",
    iataCode: "VKO",
    name: "Moscow Vnukovo International",
    city: "Moscow",
    longitude: 37.2730556,
    latitude: 55.5991667,
    timezone: "Europe/Moscow",
    countryCode: "RU",
    __v: 0,
  },
];

export default async function setup() {
  const models = airports.map((airport) => new AirportInfoModel(airport));
  try {
    await AirportInfoModel.bulkSave(models);
  } catch (err) {
    console.log(err);
  }
}
