import { AirportInfoModel } from "../../src/models/AirportInfo.mjs";

const airports = [
  {
    _id: "5f9f7b3b9d3b3c1b1c9b4b4c",
    airport_code: "KSEA",
    name: "Seattle-Tacoma Intl",
    location: "Seattle, WA",
    latitude: 47.4498889,
    longitude: -122.3117778,
    timezone: "America/Los_Angeles",
    timezone_offset_sec: -25200,
    elevation_ft: 433,
    classification: 1,
    active: true,
    delay_index_url: "https://flightaware.com/commercial/flightxml/data/airportdelays",
    weather_url: "https://flightaware.com/commercial/flightxml/data/weather",
    satellite: true,
    site: "SEA",
    iata: "SEA",
    icao: "KSEA",
    faa: "SEA",
    type: "large_airport",
    wikipedia: "http://en.wikipedia.org/wiki/Seattle-Tacoma_International_Airport",
    keywords: "SEA, KSEA, Seattle-Tacoma Intl, Boeing Field, King County Intl",
    magneticDeclination: -15.23,
  },
  {
    _id: "5f9f7b3b9d3b3c1b1c9b4b4b",
    airport_code: "KPDX",
    name: "Portland Intl",
    location: "Portland, OR",
    latitude: 45.5887089,
    longitude: -122.5968694,
    timezone: "America/Los_Angeles",
    timezone_offset_sec: -25200,
    elevation_ft: 31,
    classification: 1,
    active: true,
    delay_index_url: "https://flightaware.com/commercial/flightxml/data/airportdelays",
    weather_url: "https://flightaware.com/commercial/flightxml/data/weather",
    satellite: false,
    site: "PDX",
    iata: "PDX",
    icao: "KPDX",
    faa: "PDX",
    type: "large_airport",
    wikipedia: "http://en.wikipedia.org/wiki/Portland_International_Airport",
    keywords: "PDX, KPDX, Portland Intl",
    magneticDeclination: -14.85242,
  },
  {
    _id: "5f9f7b3b9d3b3c1b1c9b4b4d",
    airportCode: "KSLE",
    alternateIdent: "SLE",
    icaoCode: "KSLE",
    iataCode: null,
    lidCode: "SLE",
    name: "Mcnary Fld",
    type: "Airport",
    elevation: 213,
    city: "Salem",
    state: "OR",
    longitude: -123.0025,
    latitude: 44.9095278,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    wikiUrl: "http://en.wikipedia.org/wiki/McNary_Field",
    airportFlightsUrl: "/airports/KSLE/flights",
    alternatives: [],
    magneticDeclination: -14.76194,
    __v: 0,
  },
  {
    _id: "5f9f7b3b9d3b3c1b1c9b4b4e",
    airportCode: "KPDT",
    alternateIdent: "PDT",
    icaoCode: "KPDT",
    iataCode: "PDT",
    lidCode: "PDT",
    name: "Eastern Oregon Rgnl",
    type: "Airport",
    elevation: 1494,
    city: "Pendleton",
    state: "OR",
    longitude: -118.8433686,
    latitude: 45.6950953,
    timezone: "America/Los_Angeles",
    countryCode: "US",
    wikiUrl: "http://en.wikipedia.org/wiki/Eastern_Oregon_Regional_Airport",
    airportFlightsUrl: "/airports/KPDT/flights",
    alternatives: [],
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0ad7249",
    airportCode: "KATL",
    icaoCode: "KATL",
    iataCode: "ATL",
    name: "Hartsfield - Jackson Atlanta International",
    city: "Atlanta",
    state: "Georgia",
    longitude: -84.427864,
    latitude: 33.6367,
    timezone: "America/New_York",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0adb1ce",
    airportCode: "CYVR",
    icaoCode: "CYVR",
    iataCode: "YVR",
    name: "Vancouver International",
    city: "Vancouver ",
    state: "British Columbia",
    longitude: -123.183889,
    latitude: 49.194722,
    timezone: "America/Vancouver",
    countryCode: "CA",
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0ad6f06",
    airportCode: "KBZN",
    icaoCode: "KBZN",
    iataCode: "BZN",
    name: "Bozeman Yellowstone International",
    city: "Bozeman",
    state: "Montana",
    longitude: -111.15026,
    latitude: 45.777236,
    timezone: "America/Denver",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0ad9bd0",
    airportCode: "CYWG",
    icaoCode: "CYWG",
    iataCode: "YWG",
    name: "Winnipeg James Armstrong Richardson International Airport",
    city: "Winnipeg",
    state: "Manitoba",
    longitude: -97.2400944,
    latitude: 49.9100111,
    timezone: "America/Winnipeg",
    countryCode: "CA",
    __v: 0,
  },
  {
    _id: "65db0b6cfede15b9d0ad48a6",
    airportCode: "KDEN",
    icaoCode: "KDEN",
    iataCode: "DEN",
    name: "Denver International",
    city: "Denver",
    state: "Colorado",
    longitude: -104.673167,
    latitude: 39.861667,
    timezone: "America/Denver",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0ad72bc",
    airportCode: "KMCI",
    icaoCode: "KMCI",
    iataCode: "MCI",
    name: "Kansas City International",
    city: "Kansas City",
    state: "Missouri",
    longitude: -94.713889,
    latitude: 39.297611,
    timezone: "America/Chicago",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6cfede15b9d0ad5b1a",
    airportCode: "KDTW",
    icaoCode: "KDTW",
    iataCode: "DTW",
    name: "Detroit Metro Wayne County",
    city: "Detroit",
    state: "Michigan",
    longitude: -83.353393,
    latitude: 42.212431,
    timezone: "America/Detroit",
    countryCode: "US",
    __v: 0,
  },
  {
    _id: "65db0b6dfede15b9d0ad957b",
    airportCode: "KBIL",
    icaoCode: "KBIL",
    iataCode: "BIL",
    name: "Billings Logan International",
    city: "Billings",
    state: "Montana",
    longitude: -108.543544,
    latitude: 45.807849,
    timezone: "America/Denver",
    countryCode: "US",
    __v: 0,
  },
];

export default async function setup() {
  const models = airports.map((airport) => new AirportInfoModel(airport));
  try {
    await AirportInfoModel.bulkSave(models);
  } catch (err) {
    console.log(err);
  }
}
