use("plan-verifier");

db.extendedairportinfo.deleteMany({});

db.extendedairportinfo.insertMany([
  {
    airportCode: "KPDT",
    defaultInitialAltitudeText: "Maintain 7,000",
    defaultExpectInMinutesText: "5 minutes",
    initialAltitude: 70,
    initialPhrasing: "Maintain",
    expectInMinutes: 5,
    hasSIDs: false,
    expectRequired: true,
  },
  {
    airportCode: "KPDX",
    heavyRunways: ["10R", "28L"],
  },
  {
    airportCode: "KMWH",
    defaultInitialAltitudeText: "Maintain 10,000",
    defaultExpectInMinutesText: "5 minutes",
    initialAltitude: 100,
    initialPhrasing: "Maintain",
    expectInMinutes: 5,
    expectRequired: true,
    hasSIDs: false,
  },
  {
    airportCode: "KFHR",
    defaultInitialAltitudeText: "Maintain 4,000",
    defaultExpectInMinutesText: "5 minutes",
    initialAltitude: 40,
    initialPhrasing: "Maintain",
    expectInMinutes: 5,
    expectRequired: true,
    hasSIDs: false,
  },
  {
    airportCode: "KPUW",
    defaultInitialAltitudeText: "Maintain 7,000",
    defaultExpectInMinutesText: "5 minutes",
    initialAltitude: 70,
    initialPhrasing: "Maintain",
    expectInMinutes: 5,
    expectRequired: true,
    hasSIDs: false,
  },
  {
    airportCode: "KPWT",
    defaultInitialAltitudeText: "Maintain 4,000",
    defaultExpectInMinutesText: "5 minutes",
    initialAltitude: 40,
    initialPhrasing: "Maintain",
    expectInMinutes: 5,
    expectRequired: true,
    hasSIDs: false,
  },
  {
    airportCode: "KSZT",
    defaultInitialAltitudeText: "Maintain 9,000",
    defaultExpectInMinutesText: "5 minutes",
    initialAltitude: 80,
    initialPhrasing: "Maintain",
    expectInMinutes: 5,
    expectRequired: true,
    hasSIDs: false,
  },
]);
