use("plan-verifier");

db.eventreroutes.deleteMany({});
db.eventreroutes.dropIndex("departure_1");

db.eventreroutes.createIndex({ departure: 1 });
db.eventreroutes.insertMany([
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "BTG",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "OLM",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "SEA",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "TOU",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "YKM",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "LTJ",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "COUGA",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "UBG",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "ONP",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "EUG",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "OTH",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "OED",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "LMT",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "DSD",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "LKV",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "LAVAA7",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "WHAMY5",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "CASCD3",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "HRMNS6",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "EAST",
    fix: "MINNE5",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "BTG",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "OLM",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "SEA",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "TOU",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "YKM",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "LTJ",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "COUGA",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "UBG",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "ONP",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "EUG",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "OTH",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "OED",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "LMT",
    departureFrequency: "Non-noise - 126.000 (NEWBERG) / Jet and noise - 118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "DSD",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "LKV",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "LAVAA7",
    departureFrequency: "124.350 (NORTH)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "WHAMY5",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "CASCD3",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "HRMNS6",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
  {
    departure: "KPDX",
    flow: "WEST",
    fix: "MINNE5",
    departureFrequency: "118.100 (HOOD)",
    isActive: true,
  },
]);
