// The current database to use.
use("plan-verifier");

db.departures.deleteMany({});

db.departures.insertMany([
  {
    SID: "WW2",
    Fixes: ["PSC", "YKM", "MWH", "GEG", "PUW", "MQG"],
    ClimbViaSid: false,
    InitialAltitude: "80",
    ExpectTopAltitudeInMinutes: "10",
    IsRNAV: false,
  },
  {
    SID: "CBAIN1",
    ClimbViaSid: true,
    Fixes: [
      "ARRIE",
      "PAE",
      "LOFAL",
      "BANGR",
      "ZADON",
      "NORMY",
      "VAMPS",
      "BUWZO",
      "ALDER",
      "SUMMA",
      "OLM",
      "HAROB",
      "ELMAA",
    ],
    IsRNAV: true,
  },
  {
    SID: "KENT8",
    ClimbViaSid: true,
    InitialAltitude: "21",
    Fixes: ["YVR", "HUH", "YYJ", "PAE", "SEA", "OLM", "HQM", "BTG", "ELN", "YKM", "MWH", "EAT"],
    IsRNAV: false,
  },
  {
    SID: "NEEDL1",
    ClimbViaSid: true,
    Fixes: ["YVR", "HUH", "YYJ", "PAE", "SEA", "OLM", "HQM", "BTG", "ELN", "YKM", "MWH", "EAT"],
    IsRNAV: false,
  },
  {
    SID: "NRVNA1",
    ClimbViaSid: true,
    InitialAltitude: "21",
    Fixes: [
      "ARRIE",
      "PAE",
      "LOFAL",
      "BANGR",
      "ZADON",
      "NORMY",
      "VAMPS",
      "BUWZO",
      "ALDER",
      "SUMMA",
      "OLM",
      "HAROB",
      "ELMAA",
    ],
    IsRNAV: true,
  },
  {
    SID: "WHAMY4",
    Fixes: ["WHAMY", "IMB", "RIELY", "KOATA"],
    ClimbViaSid: false,
    InitialAltitude: "70",
    IsRNAV: true,
  },
  {
    SID: "CASCD2",
    Fixes: ["CHISM", "DSD", "JOGEN", "SMIGE", "PAWLI"],
    ClimbViaSid: false,
    InitialAltitude: "70",
    IsRNAV: true,
  },
  {
    SID: "HRMNS5",
    Fixes: ["HRMNS"],
    ClimbViaSid: false,
    InitialAltitude: "70",
    IsRNAV: true,
  },
  {
    SID: "LAVAA6",
    Fixes: ["LAVAA", "YKM", "PDT"],
    InitialAltitude: "70",
    IsRNAV: true,
  },
  {
    SID: "MINNE5",
    Fixes: ["MINNE", "EASON", "FAMUK", "HISKU"],
    ClimbViaSid: false,
    InitialAltitude: "70",
    IsRNAV: true,
  },
  {
    SID: "PTLD2",
    Fixes: [
      "BTG",
      "YKM",
      "LTJ",
      "PDT",
      "IMB",
      "LKV",
      "LMT",
      "DSD",
      "EUG",
      "OED",
      "OTH",
      "ONP",
      "UBG",
      "AST",
      "TOU",
      "OLM",
      "SEA",
      "LAVAA",
      "WHAMY",
      "CHISM",
      "HRMNS",
      "MINNE",
      "COUGA",
    ],
    IsRNAV: false,
  },
  {
    SID: "BANGR9",
    Fixes: ["BANGR", "PANGL", "ARRIE"],
    ClimbViaSid: true,
    InitialAltitude: "70",
    IsRNAV: true,
  },
  {
    SID: "ELMAA4",
    Fixes: ["ELMAA", "HQM", "CVO"],
    ClimbViaSid: true,
    InitialAltitude: "70",
    IsRNAV: true,
  },
  {
    SID: "HAROB6",
    Fixes: ["HAROB", "HQM", "ERAVE", "HISKU"],
    ClimbViaSid: true,
    InitialAltitude: "70",
    IsRNAV: true,
  },
  {
    SID: "JEFPO1",
    Fixes: ["ALPSE", "BANDR", "NORMY", "PAE", "ZADON"],
    ClimbViaSid: true,
    InitialAltitude: "70",
    IsRNAV: true,
  },
  {
    SID: "SUMMA2",
    Fixes: ["SUMMA", "BKE", "LKV"],
  },
  {
    SID: "MONTN2",
    ClimbViaSid: true,
    InitialAltitude: "70",
    IsRNAV: true,
  },
  {
    SID: "SEA8",
    IsRNAV: false,
    Fixes: [
      "TOU",
      "YYJ",
      "YVR",
      "HUH",
      "YDC",
      "PAE",
      "EPH",
      "ELN",
      "YKM",
      "OLM",
      "BTG",
      "UBG",
      "EUG",
      "AST",
      "HQM",
    ],
  },
  {
    SID: "PAINE6",
    IsRNAV: false,
    Fixes: ["PAE", "SEA", "EAT", "ELN", "OLM", "HQM", "NUW"],
    InitialAltitude: "20",
  },
  {
    SID: "KIENO6",
    IsRNAV: false,
    Fixes: ["KIENO", "YVR", "YYJ", "CVV"],
    InitialAltitude: "30",
  },
]);
