// The current database to use.
use("plan-verifier");

db.departures.deleteMany({});

db.departures.insertMany([
  {
    SID: "AST3",
    Telephony: "ASTORIA THREE",
    Fixes: [],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 50,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "BDN1",
    Telephony: "BEND ONE",
    Fixes: [],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 140,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "POTOR2",
    Telephony: "POTOR TWO",
    Fixes: ["POTOR"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    InitialAltitudes: [
      {
        Altitude: 60,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: false,
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "EAGLE6",
    Telephony: "EAGLE SIX",
    Fixes: [],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    InitialAltitudes: [
      {
        Altitude: 110,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: false,
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "JKSN1",
    Telephony: "JACKSON ONE",
    Fixes: ["OED"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    InitialAltitudes: [
      {
        Altitude: 110,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: false,
  },
  {
    SID: "MFR1",
    Telephony: "KLAMATH FALLS ONE",
    Fixes: ["LMT"],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 110,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "SMKKY1",
    Telephony: "SMOKY ONE",
    Fixes: ["SMKKY"],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 110,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: false,
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "CVV5",
    Telephony: "PENN COVE FIVE",
    Fixes: ["CVV", "DIGGN", "PAE"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    InitialAltitudes: [
      {
        Altitude: 20,
        AircraftClass: ".*",
      },
    ],
    isRNAV: false,
  },
  {
    SID: "NASWI2",
    Telephony: "NASWI TWO",
    Fixes: ["NUW", "HUH", "STILY", "PAE", "CVV", "DIGGN", "YETII", "MCCUL", "DISCO", "TOU", "UQQ"],
    InitialPhrasing: "ClimbViaDepartureExceptMaintain",
    InitialAltitudes: [
      {
        Altitude: 20,
        AircraftClass: ".*",
      },
    ],
    isRNAV: false,
  },
  {
    SID: "YELM5",
    Telephony: "YELM FIVE",
    Fixes: ["OLM", "HQM", "TOU", "PAE", "SEA", "YKM", "BTG", "UBG"],
    InitialPhrasing: "ClimbViaSid",
    InitialAltitudes: [
      {
        Altitude: 30,
        AircraftClass: ".*",
      },
    ],
    isRNAV: false,
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "OTH7",
    Telephony: "NORTH BEND SEVEN",
    Fixes: ["OTH", "GAMMA", "RARES", "SCOTY", "DEROY", "LEDGE"],
    InitialPhrasing: "Maintain",
    isRNAV: false,
    ExpectRequired: true,
    ExpectInMinutes: 5,
    InitialAltitudes: [
      {
        Altitude: 50,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "PSC7",
    Telephony: "TRI-CITIES SEVEN",
    Fixes: ["PSC", "GEG", "PUW", "MQG", "ALW", "PDT", "LTJ", "YKM", "ELN", "EAT", "EPH", "MWH"],
    InitialPhrasing: "ClimbViaSid",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 100,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "RDM3",
    Telephony: "REDMOND THREE",
    Fixes: ["DSD", "IMB", "ILR", "LKV", "LMT", "OED", "EUG", "CVO", "UBG", "BTG", "LTJ", "PDT"],
    InitialPhrasing: "Maintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 140,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "BELVU4",
    Telephony: "BELLEVUE FOUR",
    Fixes: [],
    InitialPhrasing: "ClimbViaSid",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 30,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "RENTN3",
    Telephony: "RENTON THREE",
    Fixes: [],
    InitialPhrasing: "ClimbViaSid",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 30,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "FELTS4",
    Telephony: "FELTS FOUR",
    Fixes: ["GEG", "COE", "MLP", "PUW", "MQG", "ALW", "PDT", "PSC", "YKM", "MWH", "EPH", "HUH"],
    InitialPhrasing: "ClimbViaSid",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 120,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 10,
  },
  {
    SID: "HAYDE4",
    Telephony: "HAYDEN FOUR",
    Fixes: [],
    InitialPhrasing: "ClimbViaSid",
    isRNAV: false,
    ExpectRequired: true,
    ExpectInMinutes: 5,
    InitialAltitudes: [
      {
        Altitude: 120,
        AircraftClass: ".*",
      },
    ],
  },
  {
    SID: "MNITO1",
    Telephony: "MANITO ONE",
    Fixes: ["GEG"],
    InitialPhrasing: "Maintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 120,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "SLE4",
    Telephony: "SALEM FOUR",
    Fixes: ["UBG", "BTG", "SL", "CVO", "DSD", "EUG", "ONP"],
    InitialPhrasing: "Maintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 90,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 10,
  },
  {
    SID: "ALDER2",
    Telephony: "ALDER TWO",
    Fixes: ["ALDER"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 30,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "MOCAA4",
    Telephony: "MOCHA FOUR",
    Fixes: ["MOCHA", "BKE", "IMB", "JINMO"],
    InitialPhrasing: "ClimbViaSid",
    isRNAV: true,
    InitialAltitudes: [
      {
        Altitude: 30,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "OLY4",
    Telephony: "OLYMPIC FOUR",
    Fixes: [],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 30,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "PUGET6",
    Telephony: "PUGET SIX",
    Fixes: [],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 30,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "TIW1",
    Telephony: "NARROWS ONE",
    Fixes: [],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 20,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "TDD3",
    Telephony: "BLUE LAKE THREE",
    Fixes: [],
    InitialPhrasing: "Maintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 40,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "GLARA2",
    Telephony: "GLARA TWO",
    Fixes: ["GLARA"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 40,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "GNNET2",
    Telephony: "NET TWO",
    Fixes: ["GNNET"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 40,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "ONP1",
    Telephony: "NEWPORT ONE",
    Fixes: ["ONP"],
    IsRNAV: false,
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 50,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "FEGBA2",
    Telephony: "FEGBA 2",
    Fixes: ["FEGBA"],
    IsRNAV: true,
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 30,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "UBG2",
    Telephony: "NEWBERG TWO",
    Fixes: ["UBG"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 40,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "GROMO4",
    Telephony: "GROMO FOUR",
    Fixes: ["TAMPO", "SIMCO", "HITCH", "GUBSE", "SUNED", "PAPPS"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 100,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "NACHE4",
    Telephony: "NACHES FOUR",
    Fixes: ["YKM", "ELN", "EAT", "EPH", "MWH", "GEG", "PSC", "ALW", "PDT", "LTJ", "BTG", "SEA"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 100,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "WENAS7",
    Telephony: "WENAS SEVEN",
    Fixes: ["TITON", "PERTT", "ELN", "RUBEL", "PAPPS", "SUNED"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    isRNAV: false,
    ExpectRequired: true,
    ExpectInMinutes: 5,
    InitialAltitudes: [
      {
        Altitude: 100,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "YKM7",
    Telephony: "YAKIMA SEVEN",
    Fixes: ["TITON"],
    InitialPhrasing: "Maintain",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 100,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "ZILLA3",
    Telephony: "ZILLA THREE",
    Fixes: [],
    InitialPhrasing: "Unknown",
    isRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 100,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "ALW2",
    Telephony: "WALLA WALLA TWO",
    Fixes: ["ALW", "YKM", "MWH", "GEG", "PUW", "MQG", "PSC", "PTD"],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 80,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 10,
    IsRNAV: false,
  },
  {
    SID: "EUG1",
    Telephony: "EUGENE ONE",
    Fixes: ["EUG", "CVO", "DSD", "LMT", "OED", "RBG", "OTH", "ONP", "UBG", "BTG"],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 90,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: false,
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "GEG7",
    Telephony: "SPOKANE 7",
    Fixes: ["GEG", "MLP", "PUW", "MQG", "ALW", "PDT", "PSC", "YKM", "MWH", "EPH", "HUH", "COE"],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 60,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: false,
    ExpectRequired: false,
    ExpectInMinutes: 10,
  },
  {
    SID: "BERNI3",
    Telephony: "BERNI THREE",
    Fixes: ["BERNI", "EASON", "EUG", "FAMUK", "HARPR"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    IsRNAV: true,
    InitialAltitudes: [
      {
        Altitude: 40,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 10,
  },
  {
    SID: "CANBY2",
    Telephony: "CANBY TWO",
    Fixes: ["CANBY"],
    InitialPhrasing: "Maintain",
    IsRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 40,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 10,
  },
  {
    SID: "CHISM4",
    Telephony: "CHISM FOUR",
    Fixes: ["CHISM", "PAWLI", "SMIGE", "JOGEN", "DSD", "RIELY", "IMB"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    IsRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 40,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 10,
  },
  {
    SID: "FARM7",
    Telephony: "FARMINGTON SEVEN",
    Fixes: ["UBG"],
    InitialPhrasing: "Maintain",
    IsRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 40,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 10,
  },
  {
    SID: "SCAPO7",
    Telephony: "SCAPO SEVEN",
    Fixes: ["SCAPO"],
    InitialPhrasing: "Maintain",
    IsRNAV: false,
    InitialAltitudes: [
      {
        Altitude: 40,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 10,
  },
  {
    SID: "CBAIN1",
    Telephony: "COBAIN ONE",
    Fixes: [
      "ARRIE",
      "PAE",
      "LOFAL",
      "BANGR",
      "ZADON",
      "NORMY",
      "VAMPS",
      "BUWZO",
      "ALDER",
      "SUMMA",
      "OLM",
      "HAROB",
      "ELMAA",
    ],
    InitialPhrasing: "ClimbViaSid",
    InitialAltitudes: [
      {
        Altitude: 21,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
    ExpectRequired: false,
    ExpectInMinutes: 3,
  },
  {
    SID: "KENT8",
    Telephony: "KENT EIGHT",
    Fixes: ["YVR", "HUH", "YYJ", "PAE", "SEA", "OLM", "HQM", "BTG", "ELN", "YKM", "MWH", "EAT"],
    IsRNAV: false,
    InitialPhrasing: "ClimbViaSid",
    InitialAltitudes: [
      {
        Altitude: 20,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 3,
  },
  {
    SID: "NEEDL1",
    Telephony: "NEEDLE ONE",
    Fixes: ["YVR", "HUH", "YYJ", "PAE", "SEA", "OLM", "HQM", "BTG", "ELN", "YKM", "MWH", "EAT"],
    IsRNAV: false,
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 21,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 3,
  },
  {
    SID: "NRVNA1",
    Telephony: "NIRVANA ONE",
    Fixes: [
      "ARRIE",
      "PAE",
      "LOFAL",
      "BANGR",
      "ZADON",
      "NORMY",
      "VAMPS",
      "BUWZO",
      "ALDER",
      "SUMMA",
      "OLM",
      "HAROB",
      "ELMAA",
    ],
    InitialPhrasing: "ClimbViaSid",
    InitialAltitudes: [
      {
        Altitude: 21,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
    ExpectRequired: false,
    ExpectInMinutes: 3,
  },
  {
    SID: "WHAMY4",
    Telephony: "WHAMY FOUR",
    Fixes: ["WHAMY", "IMB", "RIELY", "KOATA"],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
    ExpectInMinutes: 10,
    ExpectRequired: false,
  },
  {
    SID: "CASCD2",
    Telephony: "CASCADE TWO",
    Fixes: ["CHISM", "DSD", "JOGEN", "SMIGE", "PAWLI"],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
    ExpectInMinutes: 10,
    ExpectRequired: false,
  },
  {
    SID: "HRMNS5",
    Telephony: "HERMANS FIVE",
    Fixes: ["HRMNS"],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
    ExpectInMinutes: 10,
    ExpectRequired: false,
  },
  {
    SID: "LAVAA6",
    Telephony: "LAVA SIX",
    Fixes: ["LAVAA", "YKM", "PDT"],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
    ExpectInMinutes: 10,
    ExpectRequired: false,
  },
  {
    SID: "MINNE5",
    Telephony: "MINNE FIVE",
    Fixes: ["MINNE", "EASON", "FAMUK", "HISKU"],
    InitialPhrasing: "Maintain",
    ExpectInMinutes: 10,
    ExpectRequired: false,
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
  },
  {
    SID: "PTLD2",
    Telephony: "PORTLAND TWO",
    Fixes: [
      "BTG",
      "YKM",
      "LTJ",
      "PDT",
      "IMB",
      "LKV",
      "LMT",
      "DSD",
      "EUG",
      "OED",
      "OTH",
      "ONP",
      "UBG",
      "AST",
      "TOU",
      "OLM",
      "SEA",
      "LAVAA",
      "WHAMY",
      "CHISM",
      "HRMNS",
      "MINNE",
      "COUGA",
    ],
    IsRNAV: false,
    InitialPhrasing: "Maintain",
    ExpectInMinutes: 5,
    ExpectRequired: false,
    InitialAltitudes: [
      {
        Altitude: 60,
        AircraftClass: "J",
      },
      {
        Altitude: 60,
        AircraftClass: "L",
      },
      {
        Altitude: 30,
        AircraftClass: "S",
      },
    ],
  },
  {
    SID: "ELMAA4",
    Telephony: "ELMA FOUR",
    Fixes: ["ELMAA", "HQM", "CVO"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
  },
  {
    SID: "HAROB6",
    Telephony: "HAROB SIX",
    Fixes: ["HAROB", "HQM", "ERAVE", "HISKU"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
  },
  {
    SID: "ISBRG1",
    Telephony: "ICEBERG ONE",
    Fixes: ["ISBRG"],
    InitialPhrasing: "ClimbViaSid",
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "OZWLD1",
    Telephony: "OSWALD ONE",
    Fixes: ["OZWLD"],
    InitialPhrasing: "ClimbViaSid",
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "JEFPO1",
    Telephony: "JEFPO ONE",
    Fixes: ["ALPSE", "BANDR", "NORMY", "PAE", "ZADON"],
    InitialPhrasing: "ClimbViaSid",
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "SUMMA2",
    Telephony: "SUMMA TWO",
    Fixes: ["SUMMA", "BKE", "LKV"],
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
  },
  {
    SID: "MONTN2",
    Telephony: "MOUNTAIN TWO",
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    Fixes: [
      "PAE",
      "VAMPS",
      "ZADON",
      "NORMY",
      "ZELAK",
      "MODDA",
      "BANDR",
      "SEA",
      "YDC",
      "GEG",
      "MLP",
      "EPH",
      "MWH",
      "ELN",
      "ALPSE",
    ],
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: true,
  },
  {
    SID: "BANGR9",
    Telephony: "BANGOR NINE",
    IsRNAV: true,
    Fixes: ["BANGR", "PANGL", "ARRIE"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
  },
  {
    SID: "SEA8",
    Telephony: "SEATTLE EIGHT",
    IsRNAV: false,
    Fixes: [
      "SEA",
      "TOU",
      "YYJ",
      "YVR",
      "HUH",
      "YDC",
      "PAE",
      "EPH",
      "ELN",
      "YKM",
      "OLM",
      "BTG",
      "UBG",
      "EUG",
      "AST",
      "HQM",
    ],
    InitialAltitudes: [
      {
        Altitude: 70,
        AircraftClass: ".*",
      },
    ],
  },
  {
    SID: "PAINE6",
    Telephony: "PAINE SIX",
    IsRNAV: false,
    Fixes: ["PAE", "SEA", "EAT", "ELN", "OLM", "HQM", "NUW"],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 20,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "KIENO6",
    Telephony: "KIENO SIX",
    IsRNAV: false,
    Fixes: ["KIENO", "YVR", "YYJ", "CVV"],
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    InitialAltitudes: [
      {
        Altitude: 30,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 10,
  },
  {
    SID: "KLSHN1",
    Telephony: "KULSHAN ONE",
    Fixes: ["KLSHN", "CVV"],
    IsRNAV: true,
    InitialPhrasing: "ClimbViaSidExceptMaintain",
    InitialAltitudes: [
      {
        Altitude: 30,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
  {
    SID: "WATTR7",
    Telephony: "WATER SEVEN",
    Fixes: ["WATTR"],
    IsRNAV: false,
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 54,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 10,
  },
  {
    SID: "SHEDD4",
    Telephony: "SHED FOUR",
    Fixes: ["SHEDD"],
    IsRNAV: false,
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 30,
        AircraftClass: ".*",
      },
    ],
    ExpectRequired: true,
    ExpectInMinutes: 5,
  },
  {
    SID: "LMT6",
    Telephony: "KINGSLEY SIX",
    Fixes: ["LMT", "LKV", "RBL", "FMG", "FJS", "OED", "RBG", "DSD", "EUG"],
    InitialPhrasing: "Maintain",
    InitialAltitudes: [
      {
        Altitude: 100,
        AircraftClass: ".*",
      },
    ],
    IsRNAV: false,
    ExpectRequired: false,
    ExpectInMinutes: 5,
  },
]);
